# Generated by Django 3.2.12 on 2022-04-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220409_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_url',
            new_name='cover_picture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='avatar_picture',
        ),
    ]
